### ISSUE TITLE
bot times out before it can connect to workspace

### ISSUE THREAD

**Issue by kristinhortsch** [usubram/slack-quick-bots#9]
Hi! Quick question/issue I was wondering if you'd noticed before. The bot performs brilliantly when it's hooked up to a workspace with only a small number of channels and users. However, when I try to connect it to a workspace with a LARGE amount of channels and users, it takes so long fetching all the user and channel data that the bot times and never manages to connect. Have any suggestions?

**Comment by usubram** [comment]
@kristinhortsch Which version of the library are you on?

Slack enforces pagination for `/api/users.list` and `/api/channels.list` apis. You can exclude fetching the users and channel if your bot does not need it.
https://github.com/usubram/slack-quick-bots/blob/master/sample.js#L189

if your bot dependents on those data i don't think the bot would timeout (or i haven't seen happening). Share the logs if that happens. If you tail the logs while the bot is starting, you will see all the activity (paginated fetch calls) that is happening on. By design, the bot does not establish a socket connection before it finished fetching all the channels and users.  For large teams fetching the users and channels together might take a noticeable amount of time.

**Comment by usubram** [comment]
try bumping up the limit https://github.com/usubram/slack-quick-bots/blob/master/sample.js#L191 if that makes a difference.

**Comment by kristinhortsch** [comment]
@usubram version is 7.1.10? And there's no way to avoid fetching all the users? The bot doesn't need to respond directly to any of them. Might be a dumb question, sorry!

**Comment by kristinhortsch** [comment]
@usubram Ohmygosh, you're a genius! Cranked up the user limit and you're right, it definitely worked. Thank you!!!!
